create table hr_role (id int8 generated by default as identity, role_name varchar(255), primary key (id));
create table hr_user (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table if exists hr_user add constraint UK_o6vrs5l21q9mhppg2k4hntwp9 unique (email);
alter table if exists tb_user_role add constraint FKdtlsdeojbwwvhx6vmtbjbj2e foreign key (role_id) references hr_role;
alter table if exists tb_user_role add constraint FKjukoej43ra47mr41ldjr1b8wd foreign key (user_id) references hr_user;
