spring:
  application:
    name: hr-payroll
  cloud:
    loadbalancer:
      ribbon:
        enable: true

server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka

