spring:
  application:
    name: hr-payroll
  cloud:
    loadbalancer:
      ribbon:
        enable: true

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone=http: //hr-eureka-server:8761/eureka
  instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

